### ISSUE TITLE
Maybe add option to submit individual plugins/themes to mirror

### ISSUE THREAD

**Issue by demetris** [duanestorey/juniper-author#2]
Currently *Submit to Mirror* submits everything Juniper/Author has discovered.

This may not be always desirable.

So, an option to submit selected plugins/themes would be useful.

This is of course a low priority at the current stage of development.

**Comment by duanestorey** [comment]
Yah, that's something I've been thinking about.

But then again, the following are excluded:
- all private repositories are excluded, so only public ones are included
- only public repositories that have WordPress plugin headers available are included

Which means it's a WordPress plugin that's available to the public.  So in what scenario would someone want to exclude that?  I'm not opposed to putting it in, but the plugin is already publicly available for all at this point.

**Comment by demetris** [comment]
The one scenario I had in mind was a plugin that is public but at an early stage of development, and, for that reason, not ready for a wider audience yet.

You want the plugin repo to be public, in order to facilitate those who want to help with testing, but you don’t want unsuspecting folks to install the plugin and then have issues they were not prepared for. :-)

**Comment by duanestorey** [comment]
I'm likely going to make it that plugins need to have the "Authority: " header on the plugin file pointing to the server before they show up in the repo.  That makes it so only one installation of Juniper/Author can represent that plugin or theme in the repo, and delegates authority to one website to verify signed ZIPs.  I think that would work in your scenario, as you'd only add the header on production ready plugins.

**Comment by duanestorey** [comment]
This was added in 1.2.3 - you can remove individual repositories after importing them.

**Comment by duanestorey** [comment]
Thanks
