### ISSUE TITLE
Cannot access organization repos

### ISSUE THREAD

**Issue by mbanusic** [duanestorey/juniper-author#4]
Not sure how this works, because it behaves weird.

At first I created a personal access token as instructed, but that with that token I could only get my personal public repos. Then after enrolling my org for personal token I created a new one for that. But the plugin still pulls only my personal repos. At no single point did it pull organizations repos.

**Comment by duanestorey** [comment]
Right now there is a filter to make sure the repo is owned by the token owner.  I was trying to prevent two people from submitting the same plugin.  My plan to work around this is to have the Authority: header in the plugin dictate which site is going to manage it.  I may work on that piece next.  If you don't mind helping to test it out when the time comes, that would be great.  Thanks.

**Comment by duanestorey** [comment]
Any chance you can generate a read-only Github key for me to test with for your repositories?  You can hit me up on Twitter or via email?  Then I can pull in your repos temporarily to see what's going on.  Let me know, thanks.

**Comment by mbanusic** [comment]
sent

**Comment by duanestorey** [comment]
This should be fixed in 1.2.3.  Please test it out and re-open if you still have an issue. thanks
